### ISSUE TITLE
Invoke Lambda Function that uses Docker image is not supported

### ISSUE THREAD

**Issue by marshall7m** [getmoto/moto#5636] opened 2022-11-03 16:47 UTC
Moto Docker Image: motoserver/moto:4.0.9
Standalone Server: True

If a Lambda Function created within moto uses a docker image as specified within the `ImageUri` attribute, moto will break given the Lambda backend does not store a value for the function's `code_digest` attribute within this [condition](https://github.com/spulec/moto/blob/79aaf2bc030687f80d2ac977da1d5e4545eee2a0/moto/awslambda/models.py#L483).

Here's the stack trace when invoking the Lambda Function:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 335, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.7/site-packages/werkzeug/serving.py", line 322, in execute
    application_iter = app(environ, start_response)
  File "/usr/local/lib/python3.7/site-packages/moto/moto_server/werkzeug_app.py", line 249, in __call__
    return backend_app(environ, start_response)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask_cors/extension.py", line 165, in wrapped_function
    return cors_after_request(app.make_response(f(*args, **kwargs)))
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/usr/local/lib/python3.7/site-packages/moto/core/utils.py", line 111, in __call__
    result = self.callback(request, request.url, dict(request.headers))
  File "/usr/local/lib/python3.7/site-packages/moto/utilities/aws_headers.py", line 36, in _wrapper
    response = f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/moto/utilities/aws_headers.py", line 64, in _wrapper
    response = f(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/moto/awslambda/responses.py", line 123, in invoke
    return self._invoke(request)
  File "/usr/local/lib/python3.7/site-packages/moto/awslambda/responses.py", line 240, in _invoke
    function_name, qualifier, self.body, self.headers, response_headers
  File "/usr/local/lib/python3.7/site-packages/moto/awslambda/models.py", line 1892, in invoke
    payload = fn.invoke(body, headers, response_headers)
  File "/usr/local/lib/python3.7/site-packages/moto/awslambda/models.py", line 818, in invoke
    res, errored, logs = self._invoke_lambda(event=body)
  File "/usr/local/lib/python3.7/site-packages/moto/awslambda/models.py", line 720, in _invoke_lambda
    with _DockerDataVolumeContext(self) as data_vol:
  File "/usr/local/lib/python3.7/site-packages/moto/awslambda/models.py", line 114, in __enter__
    self._vol_ref = self.__class__._data_vol_map[self._lambda_func.code_digest]
AttributeError: 'LambdaFunction' object has no attribute 'code_digest'
```

**Comment by bblommers** [comment] 2022-11-03 19:56
Thanks for raising this @marshall7m - marking it as a bug.

**Comment by bblommers** [comment] 2023-02-20 23:15
Hi @marshall7m! Invoking a Lambda is only possible for images hosted in ECR, which means that the image creation in ECR would also have to be mocked by Moto.

Are you thinking of calling `docker push` against the MotoServer? Or are you using the lower-level ECR boto3-API to create layers etc manually?

**Comment by nicholasd-ff** [comment] 2023-03-22 16:43
I'm also interested in this, but not for mocking up ECR or fake pushing my local images. I've currently got a docker-compose that stands up a few lambda containers, postgres standing in for RDS and moto which is almost everything I need to test locally. 

It'd be great if I could wire the local lambdas with SQS and with event-bridge somehow to replace my shoddy glue code that handles reading from queues and shoving the result to the next lambda in line via HTTP in a format that looks like it was triggered by event bridge.

Not sure if this fits in with the moto project scope though.

**Comment by bblommers** [comment] 2023-04-05 23:34
@nicholasd-ff That sounds like you want to use AWSLambda's event source mappings? Which is partially supported by Moto. You're probably better off opening a new issue if you run into problems with this, though.

@marshall7m From what I can see you're not mocking the ECR API, which would be a requirement for this. And without a mock ECR image, this feature wouldn't actually be used by anyone. With that in mind, I'm going closing this - let me know if I've missed anything though.

**Closed by bblommers** 2023-04-05 23:34 UTC
Labels: enhancement

**Comment by benjamingorman** [comment] 2023-06-19 11:59
Just ran into this same issue.

I would like to test a Lambda which has an `ffmpeg` dependency. This has to be installed as a system dependency and therefore I believe I have to use a custom Docker image to run the Lambda - but Moto does not seem to support this.

@bblommers I believe since your last comment that a mock ECR API has now been implemented?

Would it be possible to revisit this?

**Comment by bblommers** [comment] 2023-06-22 10:55
Hey @benjamingorman, the ECR API was actually already implemented when I made the decision to close this. 

There are two technical challenges, as far as I can see:
 - creating layers from scratch to upload them manually to (Moto's) ECR
 - generating a temporary Docker image based on those bytes


Do you have a (as) small (as possible) reproducible test that succeeds against AWS? Last I checked, I couldn't find any documentation on how to get started with this. With an example test, I could have another look at this.

**Comment by AlexanderYang** [comment] 2024-07-11 16:51
My issue is a bit related, the moto doesn't support creating a CFN stack with lambda resource which uses an image:
```
boto3.client('cloudformation', region_name='eu-west-1')
cloudformation.create_stack(StackName='dummy-stack-name', TemplateBody=dummy_template_json)
```

with error **moto/awslambda/models.py:1153: KeyError** from [this line](https://github.com/getmoto/moto/blob/master/moto/awslambda/models.py#L1153)
Moto requires a lambda to have `Handler` which is not a mandatory field if a lambda is deployed as a container.
```
        # required
        spec = {
            "Code": properties["Code"],
            "FunctionName": resource_name,
            "Handler": properties["Handler"],
            "Role": properties["Role"],
            "Runtime": properties["Runtime"],
        }
```

From the [AWS doc](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-lambda-function.html#cfn-lambda-function-handler), *Handler* is not required.

> Handler
> The name of the method within your code that Lambda calls to run your function. Handler is required if the deployment package is a .zip file archive. The format includes the file name. It can also include namespaces and other qualifiers, depending on the runtime. For more information, see [Lambda programming model](https://docs.aws.amazon.com/lambda/latest/dg/foundation-progmodel.html).
> 
> Required: No
>

**Comment by bblommers** [comment] 2024-07-13 12:40
Hi @AlexanderYang, do you mind creating a new issue for this? That makes it easier to keep track of it.

If you could share the offending CFN template (or a minimum reproducible example), that would be great.

**Comment by AlexanderYang** [comment] 2024-07-14 22:36
@bblommers I've created a new issue [here](https://github.com/getmoto/moto/issues/7853).

**Comment by sqpusher** [comment] 2024-10-14 10:26
@bblommers, I am getting the same error as in the original post, where lambda invocation fails at:
```
File "/usr/local/lib/python3.7/site-packages/moto/awslambda/models.py", line 114, in __enter__
    self._vol_ref = self.__class__._data_vol_map[self._lambda_func.code_digest]
AttributeError: 'LambdaFunction' object has no attribute 'code_digest'
```
I use moto server and do create moto ECR resource and push lambda docker image to it.
