### ISSUE TITLE
Running pytest unit test using moto to mock aws lambda

### ISSUE THREAD

**Issue by karkir0003** [getmoto/moto#5846] opened 2023-01-15 01:51 UTC
This is more of a question:

I tried to write a unit test to mock aws lambda. I used the `mock_lambda` and `mock_iam` decorators to create fake aws credentials and fake iam role in order to assume permission to execute lambda. However, when I run the unit test, I get an error because my docker daemon isn't running. Also, when I try to run the test on github actions, I'm getting an error due to the payload saying "endpoint not found", but that meant that the mocked lambda function never executed. Is there a way to force the lambda to run on github actions b/c I thought that the environment github action runs on is a docker container?

Also, are there any other easier alternatives to moto that don't require installing docker and spinning up the daemon?

**Comment by bblommers** [comment] 2023-01-15 19:16
Hi @karkir0003! There is an outstanding feature request to mock lambdas without using Docker, but it is not implemented yet. See #5721 

The Lambda function should indeed be able to run within a GH action. What does the lambda look like exactly?

Keep in mind that it is not possible to connect to other services from within the Lambda, when using decorators. Because it is executed within a Docker container, it loses all mocking context.
In order to reach other services from within a Lambda, you will have to run Moto in ServerMode. See these docs for more information: http://docs.getmoto.org/en/latest/docs/services/lambda.html

**Comment by karkir0003** [comment] 2023-01-15 19:18
The lambda event handler is a simple python function that uses pandas to preprocess a csv file

**Comment by karkir0003** [comment] 2023-01-15 19:18
it runs on python 3.9 runtime environment

**Comment by bblommers** [comment] 2023-01-15 19:30
Is your project open source? Or can you create a reproducible test on Github that shows the error? That would make it easier to debug.

**Comment by karkir0003** [comment] 2023-01-15 20:01
yes. here is the link to the failing test: https://github.com/DSGT-DLP/Deep-Learning-Playground/actions/runs/3920486928/jobs/6702151759

**Comment by bblommers** [comment] 2023-01-15 20:22
This is the relevant error msg: `manifest for lambci/lambda:python3.9 not found:`

Moto uses the Docker-images from `lambci`, as they closely resemble what AWS provides - but they do not have images for the latest Python versions.

Can you try running the same tests with this environment variable set? `MOTO_DOCKER_LAMBDA_IMAGE=mLupin/docker-lambda`
That pulls the Docker images from a different source, which does have the latest Python-versions.

**Comment by karkir0003** [comment] 2023-01-15 20:57
so then in the github actions, I have to set this environment variable as a secret of some sort or is there an alternative function I can use that doesn't force me to set a local environment variable? @bblommers

**Comment by karkir0003** [comment] 2023-01-15 21:10
I also tried on local end adding an `os.environ["MOTO_DOCKER_LAMBDA_IMAGE"] = "mLupin/docker-lambda` and I'm getting same error on local

**Comment by bblommers** [comment] 2023-01-15 21:15
> so then in the github actions, I have to set this environment variable 

Yes - there is no alternative function/way to do this. In the future this option, to use `mLupin` as the provider, should become the default though.

**Comment by bblommers** [comment] 2023-02-01 10:19
> I also tried on local end adding an `os.environ["MOTO_DOCKER_LAMBDA_IMAGE"] = "mLupin/docker-lambda` and I'm getting same error on local

Apologies for the delay in this @karkir0003 - but the docs are actually wrong. The Docker repository should be in all lower-case:
`os.environ["MOTO_DOCKER_LAMBDA_IMAGE"] = "mlupin/docker-lambda`

**Comment by karkir0003** [comment] 2023-02-01 14:58
so then the moto should work as normal with this change?

**Comment by bblommers** [comment] 2023-02-01 15:00
That should mean the Lambda function gets executed, yes.

**Comment by karkir0003** [comment] 2023-02-03 01:40
@bblommers tried making that fix, but got this error:

```
"error running docker: Error while fetching server API version: (2, 'CreateFile', 'The system cannot find the file specified.')"
```

**Comment by bblommers** [comment] 2023-02-03 12:03
That looks like a generic Docker error @karkir0003 - see https://stackoverflow.com/questions/66332803/i-am-getting-error-while-running-docker-compose-up-in-windows-server-2016 or the first comment on this question: https://stackoverflow.com/questions/64952238/docker-errors-dockerexception-error-while-fetching-server-api-version

**Comment by karkir0003** [comment] 2023-02-03 18:21
I was running in github actions and got this error as well

**Comment by bblommers** [comment] 2023-02-03 23:28
Your outstanding PR is currently failing because the `create_function` needs a ZipFile, not the python-file itself.
This diff fixes that: https://github.com/DSGT-DLP/Deep-Learning-Playground/compare/test-preprocess-lambda...bblommers:Deep-Learning-Playground:use-zip-file

The build output from that branch is here: https://github.com/bblommers/Deep-Learning-Playground/actions/runs/4088579516/jobs/7050406096
That contains the following failure: `Unable to import module \'lambda_function\': No module named \'pandas\'`

The good news: the Lambda is actually being executed inside a Docker-container!
The bad news is that the `pandas`-module is not part of the packaged module, and also not part of the basic Docker image, so this code will never run. (Executing the function code in AWS gives the same error, fwiw.)

As far as I know, there are two ways around this:
 - create a zip-file that also contains the pandas-module
 - configure a LambdaLayer that contains the `pandas`-module. [This is not yet supported by Moto.](https://github.com/getmoto/moto/issues/3779)

**Comment by karkir0003** [comment] 2023-02-03 23:36
Hi @bblommers. Thank you so much for the help so far! I greatly appreciate it. For the first workaround "create a zip-file that also includes the pandas-module", can you point me to an example of how I could do that?

**Comment by bblommers** [comment] 2023-02-04 00:19
I don't have any examples on how to set that up @karkir0003- it's been years since I had to do it. Google may be your best bet here.

**Comment by karkir0003** [comment] 2023-02-04 02:56
ok. I'm taking a look. I saw this way where you can use `pd.__file__` to get the pandas file, upload into mocked s3 bucket and then create the layer by passing in the mocked s3 bucket and key. I tried that and I'm still getting `module not found: pandas`. I continued off of the diff you posted

**Comment by bblommers** [comment] 2023-03-04 13:27
As far as I can tell, there's nothing else for Moto to do here, so I'm going to close this. Feel free to open a new issue if you encounter any other bugs/issues!

**Closed by bblommers** 2023-03-04 13:27 UTC
Labels: question, debugging
