### ISSUE TITLE
mock_lambda missing PackageType attribute

### ISSUE THREAD

**Issue by omerls-pw** [getmoto/moto#7108] opened 2023-12-10 12:00 UTC
I'm trying to test against zip based only lambdas, but the return object is missing `PackageType`.

test:
```python
    @mock_lambda
    def test_list_zipped_lambdas(self):
        self.setup_mock_iam_role()

        # with mock_lambda():
        client = boto3.client("lambda", region_name="us-east-1")
        client.create_function(
            FunctionName="test_function",
            Runtime="python3.8",
            Role="arn:aws:iam::123456789012:role/test-role",
            Handler="lambda_function.lambda_handler",
            Code={"ZipFile": b"fake code"},
            Description="Test function",
        )
```

Tested code:
```python
def list_zipped_lambdas(client):
    non_image_based_lambdas = []
    functions = client.list_functions(MaxItems=2000)
    for function in functions["Functions"]:
        if "PackageType" in function and function["PackageType"] != "Image":
            non_image_based_lambdas.append(function)

    return non_image_based_lambdas
```

When I ran it, `list_zipped_lambdas` yield None, since the attribute `PackageType` is missing.

I printed the results out:
```json
{
    "ResponseMetadata": {
        "HTTPStatusCode": 200,
        "HTTPHeaders": {},
        "RetryAttempts": 0
    },
    "Functions": [
        {
            "FunctionName": "test_function",
            "FunctionArn": "arn:aws:lambda:us-east-1: 123456789012:function:test_function:$LATEST",
            "Runtime": "python3.8",
            "Role": "arn:aws:iam: : 123456789012:role/test-role",
            "Handler": "lambda_function.lambda_handler",
            "CodeSize": 9,
            "Description": "Test function",
            "Timeout": 3,
            "MemorySize": 128,
            "LastModified": "2023-12-10T11: 45: 15.659570000Z",
            "CodeSha256": "0TNilO7vOujahhpKZUxA53zQgu3yqjTy6dXDQh6PNZk=",
            "Version": "$LATEST",
            "VpcConfig": {
                "SubnetIds": [],
                "SecurityGroupIds": []
            },
            "TracingConfig": {
                "Mode": "PassThrough"
            },
            "Layers": [],
            "State": "Active",
            "LastUpdateStatus": "Successful",
            "Architectures": [
                "x86_64"
            ],
            "EphemeralStorage": {
                "Size": 512
            },
            "SnapStart": {
                "ApplyOn": "None",
                "OptimizationStatus": "Off"
            }
        }
    ]
}
```

Packages:
* moto 4.2.11
* boto3 1.33.11

**Comment by bblommers** [comment] 2023-12-10 13:35
Hi @omerls-pw, welcome to Moto, and thanks for raising this.

If PackageType is specified during creation, we do return this value - so I _think_ the problem is that we do not return a default value. Marking it as a bug.

**Closed** 2023-12-10 20:31 UTC
Labels: bug

**Comment by omerls-pw** [comment] 2023-12-10 21:34
Wow!
