### ISSUE TITLE
Responses as context manager gets overridden if Moto context managers are set up afterwards

### ISSUE THREAD

**Issue by CaptainDriftwood** [getmoto/moto#6417] opened 2023-06-16 18:51 UTC
If both Moto and responses are set up as context managers, if responses is set up prior to Moto, then any mocked responses from the requests library will be dropped.

Python version: 3.9.16

```text
moto==4.1.11
responses==0.23.1
boto3==1.26.153
requests==2.31.0
```

```python
import boto3
import moto
import pytest
import requests
import responses

url = "https://www.example1234567890.com"


@pytest.fixture(autouse=True)
def aws_credentials(monkeypatch):
    """Mocked AWS Credentials for moto."""

    monkeypatch.setenv("AWS_ACCESS_KEY_ID", "testing")
    monkeypatch.setenv("AWS_SECRET_ACCESS_KEY", "testing")
    monkeypatch.setenv("AWS_SECURITY_TOKEN", "testing")
    monkeypatch.setenv("AWS_SESSION_TOKEN", "testing")


def code_under_test():
    client = boto3.resource("s3")
    bucket = client.Bucket("mybucket")
    bucket.Object("my_file.json").get()["Body"].read()
    data = requests.get(url).json()
    assert data == {"foo": "bar"}


@responses.activate
@moto.mock_s3
def test_with_decorators():
    client = boto3.client("s3")
    client.create_bucket(Bucket="mybucket")
    client.put_object(Bucket="mybucket", Key="my_file.json", Body=b"{}")
    responses.add(responses.GET, url, json={"foo": "bar"})

    code_under_test()


@moto.mock_s3
@responses.activate
def test_with_decorators_alternate():
    client = boto3.client("s3")
    client.create_bucket(Bucket="mybucket")
    client.put_object(Bucket="mybucket", Key="my_file.json", Body=b"{}")
    responses.add(responses.GET, url, json={"foo": "bar"})

    code_under_test()


def test_with_context_managers():
    with moto.mock_s3():
        with responses.RequestsMock(assert_all_requests_are_fired=False) as rsps:
            client = boto3.client("s3")
            client.create_bucket(Bucket="mybucket")
            client.put_object(Bucket="mybucket", Key="my_file.json", Body=b"{}")
            rsps.add(responses.GET, url, json={"foo": "bar"})

            code_under_test()


# When responses is run as a context manager first, alongside moto as a context manager,
# the mocked requests get overriden.
def test_with_context_managers_alternate():
    with responses.RequestsMock(assert_all_requests_are_fired=False) as rsps:
        with moto.mock_s3():
            client = boto3.client("s3")
            client.create_bucket(Bucket="mybucket")
            client.put_object(Bucket="mybucket", Key="my_file.json", Body=b"{}")
            rsps.add(responses.GET, url, json={"foo": "bar"})

            code_under_test()
```

This is closely related to #4870

**Comment by bblommers** [comment] 2023-06-22 13:36
Hi @Jasonca2, thanks for raising this. I'm not sure whether this is something that Moto can fix - it looks like that's just how `responses` works. 

I've raised an issue with them to see if/how this can be solved:  https://github.com/getsentry/responses/issues/645

**Comment by beliaev-maksim** [comment] 2023-06-22 16:27
@Jasonca2 
`responses` maintainer here

yes, from the code that you supplied it will not work together nicely. Since `requests` adapter will not know what to do and which mocks to call.

@bblommers 
I am not sure how `moto` is structured. But can you maybe expose `responses` registry to the user? Then it should work. 
like 

```python
with moto.mock_s3() as m1:
    m1.responses_registry.add(Response())
```

or did you completely override the `RequestMock` object ?

**Comment by beliaev-maksim** [comment] 2023-06-22 16:59
yea, entirely different registry is not gonna play nicely 

what I do not understand is does this test work? and only reversed order fails ?

or all tests fail?

```python
def test_with_context_managers():
    with moto.mock_s3():
        with responses.RequestsMock(assert_all_requests_are_fired=False) as rsps:
            client = boto3.client("s3")
            client.create_bucket(Bucket="mybucket")
            client.put_object(Bucket="mybucket", Key="my_file.json", Body=b"{}")
            rsps.add(responses.GET, url, json={"foo": "bar"})

            code_under_test()
```

**Comment by beliaev-maksim** [comment] 2023-06-22 17:12
@bblommers 
another idea, a bit wild but I do it in `responses` for some testing purposes

if you have two nested decorators, the problem is that you reach one decorator which does not have registered responses.

you need to allow all the traffic (expect essential for `moto`) and pass through it

I opened an issue https://github.com/getmoto/moto/issues/6433

then user defined Mock will catch it

**Comment by bblommers** [comment] 2023-06-22 22:23
> what I do not understand is does this test work? and only reversed order fails ?
> 
That breaks the other way actually. URL's defined by the user are intercepted, but not Moto's URLs.

> you need to allow all the traffic (expect essential for moto) and pass through it
>

I understand why it could work.. but it doesn't behave as I would expect.
With the `test_with_context_managers_alternate`, and matching the exact URL (`add_passthru("https://www.example1234567890.com")`, the URL is not intercepted by `responses` - I get a ConnectionError because the website does not exist.

**Comment by beliaev-maksim** [comment] 2023-06-22 22:54
@bblommers and passthru is registered inside `moto` ?

the idea behind is that moto will pass requests as regular request, but on the second level it will be caught by regular `responses`

**Comment by bblommers** [comment] 2023-06-23 11:37
@beliaev-maksim This is the equivalent stand-alone test case (so without Moto), I believe?
```
def test_with_context_managers_alternate():
    import re
    with responses.RequestsMock(assert_all_requests_are_fired=False) as rsps:

        moto_mock = responses.RequestsMock(assert_all_requests_are_fired=False)
        moto_mock.add_passthru(url)
        moto_mock.start()
        rsps.add(responses.GET, url, json={"foo": "bar"})

        data = requests.get(url).json()
        assert data == {"foo": "bar"}

        moto_mock.stop()
```
Still the `ConnectionError`. Changing the passthrough to `re.compile(".*")` doesn't work either

**Comment by beliaev-maksim** [comment] 2023-06-23 17:03
@bblommers
Right, just ran your example in debugger

I have some idea, but will require "responses" update

Still researching

**Comment by Jasonca2** [comment] 2023-06-26 23:55
@beliaev-maksim & @bblommers 
Thanks for looking into this.

**Comment by bblommers** [comment] 2023-09-01 18:13
Do you have any updates on this, @beliaev-maksim? I saw the `unbound_send` PR you created, but I'm not familiar enough with the inner workings of `responses` to see if/how that can be used here.

**Comment by beliaev-maksim** [comment] 2023-09-01 20:09
@bblommers 
oh, sorry for that, got busy with my main work :D
thanks for the reminder.

yes, with this PR merged it should be possible to do following:

```python
import responses
import requests


def test_with_context_managers_alternate():
    url = "https://www.example1234567890.com"
    moto_url = "https://www.moto.com"
    with responses.RequestsMock(assert_all_requests_are_fired=False) as rsps:

        moto_mock = responses.RequestsMock(assert_all_requests_are_fired=False)
        moto_mock.start()
        moto_mock.add_passthru(url)

        responses._real_send = rsps.unbound_on_send()

        moto_mock.add(responses.GET, moto_url, json={"moto": "mock"})
        rsps.add(responses.GET, url, json={"foo": "bar"})

        data = requests.get(url).json()
        assert data == {"foo": "bar"}

        data1 = requests.get(moto_url).json()
        assert data1 == {"moto": "mock"}

        moto_mock.stop()
```

will that snippet be sufficient for you to proceed with updating docs/code for moto?
basically, the idea is that now we overwrite the value of real send and next time when moto tries to send a real request it will hit the `rsps` decorator.

if that is not sufficient, can you please provide another simplified code snippet that I can play and debug

**Comment by bblommers** [comment] 2023-09-01 20:33
Ah, gotcha - thanks for the snippet @beliaev-maksim. We don't have access to `rsps` within Moto, so that's not something that can be fixed in our codebase. But just adding the `responses._real_send = rsps.unbound_on_send()` fixes the problem for the OP.

@Jasonca2 Is this an acceptable workaround for you? All the tests from your example pass, by just adding that one line.

**Closed** 2023-11-04 15:21 UTC
Labels: debugging
