### ISSUE TITLE
ECS run_task in  fargate mode

### ISSUE THREAD

**Issue by shubozhang** [getmoto/moto#2101] opened 2019-03-11 11:28 UTC
Is there a way to mock ecs run_task in fargate mode? Currently, I only find EC2 mode. Thanks !

**Comment by spulec** [comment] 2019-07-09 01:18
Thanks for opening.

Not today, but I am going to set this as a feature request.

**Comment by FishmanL** [comment] 2020-06-08 15:16
Seconding this!

**Comment by mracette** [comment] 2021-04-24 17:36
It's been a while since this request, just wondering if it's still on the roadmap? Thanks!

**Comment by bblommers** [comment] 2021-04-25 13:55
Hi @mracette, moto is really a community-driven project, so there's no roadmap as such. Features just get added by people who want to contribute/really need that specific feature. So if somebody feels like developing this - PR's are always welcome!

**Comment by bblommers** [comment] 2021-12-27 21:47
There's been quite some improvements to ECS since this was raised, including in #3584, and we do have internal tests that call `run_task(launchType="FARGATE")`, so I'm going to assume that this now works as intended.

I'll close this, but do let us know if there are still issues with our current implementation.

**Comment by szczeles** [comment] 2022-04-11 13:05
@bblommers Unfortunately, it still doesn't work, I just faced the issue in 3.1.4 release.

The [internal test](https://github.com/spulec/moto/blob/3.1.4/tests/test_ecs/test_ecs_boto3.py#L1730) calling `run_task(launchType="FARGATE")` actually registers instance before, so simulates EC2 launch type, not the Fargate launch. If you drop `client.register_container_instance` from the test, it will stop to work, as `run_task` [assumes EC2 run](https://github.com/spulec/moto/blob/3.1.4/moto/ecs/models.py#L981). I think I can contribute a fix for this case.

**Comment by bblommers** [comment] 2022-04-11 19:08
Hi @szczeles, thanks for letting us know. A PR would be very welcome - let me know if you need any help around this!

**Closed** 2023-01-29 23:47 UTC
Labels: enhancement
