### ISSUE TITLE
RDS: Global Cluster not associating secondary clusters

### ISSUE THREAD

**Issue by kevho48** [getmoto/moto#6260] opened 2023-04-26 17:06 UTC
Moto ==4.1.9.dev13

Global cluster's cluster members is missing secondary clusters when a global cluster is assigned a primary cluster.

Replicate - 
Create primary cluster with `create_db_cluster` in `us-east-1`
Create secondary cluster with `create_db_cluster` in `us-west-2` with the primary cluster's arn as `ReplicationSourceIdentifier`
*Note that the secondary cluster is now added under the primary cluster's `ReadReplicaIdentifiers`

Create global database with `SourceDBClusterIdentifier` as the primary cluster's arn.
The global database will have the primary cluster listed as a cluster member, but the secondary cluster is missing from the list.

**Comment by kevho48** [comment] 2023-04-26 17:07
This happens regardless of region, if the secondary cluster is created in `us-east-1` the bug happens anyway

**Comment by rafcio19** [comment] 2023-05-20 22:59
@bblommers I can take a look at this

**Comment by rafcio19** [comment] 2023-05-23 15:33
@kevho48 I am not able replicate the behaviour for your first scenario. In AWS, if I follow these steps and call `describe_global_clusters` then only the 1st cluster is listed in `GlobalClusterMembers`:

```
import boto3
import json
from time import sleep

c = boto3.client('rds', 'eu-west-1')

cluster_id = 'test1'
db_subnet_group = 'default-vpc-8e69a9e9'

print('creating cluster1')
c.create_db_cluster(
    DBClusterIdentifier=cluster_id, Engine='aurora-mysql',
    DBSubnetGroupName=db_subnet_group, DBClusterParameterGroupName='raf-test',
    MasterUsername='test', MasterUserPassword='MasterUserPassword',
    # AvailabilityZones=['eu-west-1a', 'eu-west-1b']
)

print('creating instance1')
c.create_db_instance(
                DBInstanceIdentifier=f'{cluster_id}-i1',
                DBInstanceClass='db.r5.large',
                Engine='aurora-mysql',
                PubliclyAccessible=False,
                AvailabilityZone='eu-west-1a',
                DBSubnetGroupName=db_subnet_group,
                DBClusterIdentifier=cluster_id,
            )

# wait for instance to come up..
while True:
    resp = c.describe_db_instances(DBInstanceIdentifier=f'{cluster_id}-i1')
    if resp["DBInstances"][0]['DBInstanceStatus'] == 'available':
        break
    sleep(10)

c2 = boto3.client('rds', 'eu-west-2')
cluster_id2 = 'test2'
db_subnet_group2 = 'test'


print('creating cluster2')
c2.create_db_cluster(
    DBClusterIdentifier=cluster_id2, Engine='aurora-mysql',
    DBSubnetGroupName=db_subnet_group2,
    ReplicationSourceIdentifier=f'arn:aws:rds:eu-west-1:1234567890:cluster:{cluster_id}'
)

print('creating instance2')
c2.create_db_instance(
                DBInstanceIdentifier=f'{cluster_id2}-i1',
                DBInstanceClass='db.r5.large',
                Engine='aurora-mysql',
                PubliclyAccessible=False,
                AvailabilityZone='eu-west-2a',
                DBSubnetGroupName='test',
                DBClusterIdentifier=cluster_id2,
            )

# wait for instance to come up..
while True:
    resp = c2.describe_db_instances(DBInstanceIdentifier=f'{cluster_id2}-i1')
    if resp["DBInstances"][0]['DBInstanceStatus'] == 'available':
        break
    sleep(10)

print('creating global cluster')
c.create_global_cluster(
    GlobalClusterIdentifier='global',
    SourceDBClusterIdentifier=f'arn:aws:rds:eu-west-1:1234567890:cluster:{cluster_id}',
)

resp = c2.describe_global_clusters()
print(json.dumps(resp, indent=2, default=str))


```
Output:
```
[
  {
    "GlobalClusterIdentifier": "global",
    "GlobalClusterResourceId": "cluster-036bf968fb5480e7",
    "GlobalClusterArn": "arn:aws:rds::1234567890:global-cluster:global",
    "Status": "available",
    "Engine": "aurora-mysql",
    "EngineVersion": "5.7.mysql_aurora.2.11.2",
    "StorageEncrypted": false,
    "DeletionProtection": false,
    "GlobalClusterMembers": [
      {
        "DBClusterArn": "arn:aws:rds:eu-west-1:1234567890:cluster:test1",
        "Readers": [],
        "IsWriter": true
      }
    ]
  }
]
```

Is this the scenario you had in mind?

**Comment by kevho48** [comment] 2023-05-26 14:50
that's a little strange, it should have both clusters as global cluster members.

**Comment by rafcio19** [comment] 2023-05-26 18:23
Perhaps I am missing some steps 🤔 
If you can reproduce the desired behaviour then please post the steps. Ideally it would  boto3 code to ensure we are both looking at the same stuff.

**Comment by rafcio19** [comment] 2023-05-31 20:19
After running ☝️ code and

```
resp = c.describe_db_clusters()
print('region 1 clusters')
print(json.dumps(resp, indent=2, default=str))

print('region 2 clusters')
resp2 = c2.describe_db_clusters()
print(json.dumps(resp2, indent=2, default=str))
```

Output, with less relevant fields removed:

```
region 1 clusters
{
  "DBClusters": [
    {
      "AllocatedStorage": 1,
      "AvailabilityZones": [
        "eu-west-1b",
        "eu-west-1a",
        "eu-west-1c"
      ],
      ...
      "ReadReplicaIdentifiers": [
        "arn:aws:rds:eu-west-2:1234567890:cluster:test2"
      ],
      "DBClusterMembers": [
        {
          "DBInstanceIdentifier": "test1-i1",
          "IsClusterWriter": true,
          "DBClusterParameterGroupStatus": "in-sync",
          "PromotionTier": 1
        }
      ],
      ....
      "DBClusterArn": "arn:aws:rds:eu-west-1:1234567890:cluster:test1",
      ...
    }
  ]
}
region 2 clusters
{
  "DBClusters": [
    {
      "AllocatedStorage": 1,
      "AvailabilityZones": [
        "eu-west-2a",
        "eu-west-2b",
        "eu-west-2c"
      ],
      ...
      "ReplicationSourceIdentifier": "arn:aws:rds:eu-west-1:1234567890:cluster:test1",
      "ReadReplicaIdentifiers": [],
      "DBClusterMembers": [
        {
          "DBInstanceIdentifier": "test2-i1",
          "IsClusterWriter": true,
          "DBClusterParameterGroupStatus": "in-sync",
          "PromotionTier": 1
        }
      ],
      ..
      "DBClusterArn": "arn:aws:rds:eu-west-2:1234567890:cluster:test2",
      ..
    }
  ]
}
```

Calling `create_global_cluster` appears to make no difference to the output.

**Comment by mayesca** [comment] 2023-06-09 13:42
Unfortunaltely AWS is a little inconsistent with cluster states. AWS cluster responses do not contain reference to the global cluster however the `describe_global_clusters` response should contain all cluster members

Describe global DB response
`{
    "GlobalClusters": [
        {
            "GlobalClusterIdentifier": "test-global-database",
            "GlobalClusterResourceId": "cluster-77eeee47cce21f24",
            "GlobalClusterArn": "arn:aws:rds::586488143756:global-cluster:test-global-database",
            "StorageEncrypted": true,
            "DeletionProtection": false,
            "GlobalClusterMembers": [
                {
                    "DBClusterArn": "arn:aws:rds:us-east-1:586488143756:cluster:test-primary-cluster",
                    "Readers": [
                        "arn:aws:rds:us-west-2:586488143756:cluster:test-secondary-cluster"
                    ],
                    "IsWriter": true
                },
                {
                    "DBClusterArn": "arn:aws:rds:us-west-2:586488143756:cluster:test-secondary-cluster",
                    "Readers": [],
                    "IsWriter": false,
                }
            ]
        }
    ]
}
`

This global DB has both a primary and secondary cluster with both listed within `GlobalClusterMembers`

**Only including some of the fields for one of the `describe-db-cluster` responses (primary cluster) since majority of the fields are the same minus a couple of values or so.

`{
    "DBClusters": [
        {
            "AllocatedStorage": 1,
            "AvailabilityZones": [
                "us-east-1a",
                "us-east-1c",
                "us-east-1d"
            ],
            "DBClusterIdentifier": "test-primary-cluster",
            "ReadReplicaIdentifiers": [
                "arn:aws:rds:us-west-2:586488143756:cluster:test-secondary-cluster"
            ],
            "DBClusterMembers": [
                {
                    "DBInstanceIdentifier": "test-primary-cluster-i1",
                    "IsClusterWriter": false,
                    "DBClusterParameterGroupStatus": "in-sync",
                    "PromotionTier": 1
                },
            ],
            "DBClusterArn": "arn:aws:rds:us-east-1:586488143756:cluster:test-primary-cluster",
            "GlobalWriteForwardingRequested": false
        }
    ]
}`

The [boto3 documentation](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/rds/client/describe_db_clusters.html) also shows that `describe_db_cluster` responses only contain two fields related to the global cluster

- `GlobalWriteForwardingStatus` & `GlobalWriteForwardingRequested`

You should be able to replicate this if you 
1. Create the global database
2. Create the primary cluster and supply [GlobalClusterIdentifier](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/rds/client/create_db_cluster.html#:~:text=AZ%20DB%20clusters-,GlobalClusterIdentifier,-(string)%20%E2%80%93).
3. Create the secondary cluster and supply `GlobalClusterIdentifier` param just like the first call

**Comment by rafcio19** [comment] 2023-06-09 15:39
Thanks for trying to clear things up @mayesca. However, without a reliable way to reproduce the desired behaviour I don't have a clear goal to aim for.

Can you provide code to reproduce desired behaviour? Feel free to take inspiration from my previous post https://github.com/getmoto/moto/issues/6260#issuecomment-1559677764

**Comment by mayesca** [comment] 2023-06-11 22:31
@rafcio19 - Code below but the main difference is order of resource creation outlined in https://github.com/getmoto/moto/issues/6260#issuecomment-1584599054

```
import boto3
import json
from time import sleep

east_client = boto3.client('rds', 'us-east-1')
west_client = boto3.client('rds', 'us-west-1')

# Create global cluster 
print('creating global db')
response = east_client.create_global_cluster(
    GlobalClusterIdentifier='test-global-db',
    Engine='aurora-mysql',
    DeletionProtection=False,
    DatabaseName='test-db',
    StorageEncrypted=False
)

#Wait for primary cluster to be come available
while True:
    resp = east_client.describe_global_clusters(GlobalClusterIdentifier="test-global-db")
    global_clusters = resp.get("GlobalClusters", None)
    if global_clusters and global_clusters[0].get('Status') == 'available':
        break
    sleep(10)

print('creating primary cluster')
east_client.create_db_cluster(
    DBClusterIdentifier="test-primary-cluster", Engine='aurora-mysql',
    GlobalClusterIdentifier="test-global-db",
    MasterUsername='testUsername', MasterUserPassword='testPassword',
)

#Wait for primary cluster to be come available
while True:
    resp = east_client.describe_db_clusters(DBClusterIdentifier="test-primary-cluster")
    db_clusters = resp.get("DBClusters", None)
    if db_clusters and db_clusters[0].get('Status') == 'available':
        break
    sleep(10)

print('creating primary cluster instance')
east_client.create_db_instance(
                DBInstanceIdentifier='test-primary-cluster-i1',
                DBInstanceClass='db.r5.large',
                Engine='aurora-mysql',
                PubliclyAccessible=False,
                DBClusterIdentifier='test-primary-cluster',
            )

# wait for primary cluster instane to come up..
while True:
    resp = east_client.describe_db_instances(DBInstanceIdentifier="test-primary-cluster-i1")
    db_instances = resp.get("DBInstances", None)
    if db_instances and db_instances[0].get("DBInstanceStatus") == 'available':
        break
    sleep(10)

print('creating secondary cluster')
west_client.create_db_cluster(
    DBClusterIdentifier="test-secondary-cluster", Engine='aurora-mysql',
    GlobalClusterIdentifier="test-global-db"
)

# wait for secondary cluster to come up..
while True:
    resp = west_client.describe_db_clusters(DBClusterIdentifier="test-secondary-cluster")
    db_clusters = resp.get("DBClusters", None)
    if db_clusters and db_clusters[0].get("Status") == 'available':
        break
    sleep(10)


resp = east_client.describe_global_clusters(GlobalClusterIdentifier="test-global-db")
print(json.dumps(resp, indent=2, default=str))

```

Output of code above. I only included the response from `describe_global_clusters` to show that it includes both the primary and secondary cluster.

```
(Playground) ☁  Playground  python3 runner.py
creating global db
creating primary cluster
creating primary cluster instance
creating secondary cluster
{
  "GlobalClusters": [
    {
      "GlobalClusterIdentifier": "test-global-db",
      "GlobalClusterResourceId": "cluster-a32a13609beaa797",
      "GlobalClusterArn": "arn:aws:rds::131439663349:global-cluster:test-global-db",
      "Status": "available",
      "Engine": "aurora-mysql",
      "EngineVersion": "5.7.mysql_aurora.2.11.2",
      "DatabaseName": "test-db",
      "StorageEncrypted": false,
      "DeletionProtection": false,
      "GlobalClusterMembers": [
        {
          "DBClusterArn": "arn:aws:rds:us-east-1:131439663349:cluster:test-primary-cluster",
          "Readers": [
            "arn:aws:rds:us-west-1:131439663349:cluster:test-secondary-cluster"
          ],
          "IsWriter": true
        },
        {
          "DBClusterArn": "arn:aws:rds:us-west-1:131439663349:cluster:test-secondary-cluster",
          "Readers": [],
          "IsWriter": false,
          "GlobalWriteForwardingStatus": "disabled"
        }
      ]
    }
  ],
}
```

<img width="1170" alt="Screen Shot 2023-06-11 at 6 29 06 PM" src="https://github.com/getmoto/moto/assets/12236147/d53e7129-418a-425d-b33a-0b3bee05f1ab">

**Comment by rafcio19** [comment] 2023-06-16 08:32
@mayesca the recent PR is now available in `4.1.12.dev31` so you could give that a shot. It should cover your use case.

@kevho48  I am not sure the PR covers what you originally requested but I would need a sample code similar to what @mayesca provided to be able to proceed.

**Comment by rafcio19** [comment] 2023-07-10 08:38
@kevho48 did you get a chance to review new moto build to see if it resolves your issue?

**Comment by bblommers** [comment] 2023-07-18 11:36
I had a look at the description as well, but I couldn't reproduce the problem. I created the two clusters in the console, and then the Global Database via the CLI. AWS displays the same behaviour:
```
The global database will have the primary cluster listed as a cluster member, but the secondary cluster is missing from the list.
```

So I'm just going to close this. Happy to reopen this if anyone can provide a reproducible script that showcases the issue.

**Closed by bblommers** 2023-07-18 11:36 UTC
Labels: enhancement
