### ISSUE TITLE
Invoking a Lambda requires docker

### ISSUE THREAD

**Issue by mwgamble** [getmoto/moto#6104] opened 2023-03-21 01:28 UTC
I want to use moto to mock invoking a Lambda in my code. However, it requires docker. My tests are already running inside of a container (using docker-in-docker in CI), which makes this infeasible.

Ideally I would be able to specify an arbitrary callable to invoke, rather than the overhead and complexity of having to run docker.

**Comment by bblommers** [comment] 2023-03-21 21:43
Hi @mwgamble! This looks like a duplicate of #5721 - so I'm going to close this in favor of that.

Like I mentioned there, it would be a useful feature, and it's own our radar, but I don't know yet how it is going to be implemented. Either as a callable, or by specifying a fixed response, or something else entirely.

**Closed by bblommers** 2023-03-21 21:43 UTC
Labels: enhancement

**Comment by mwgamble** [comment] 2023-03-21 22:03
Sorry for the duplicate. That didn't turn up in my search because the word "invoke" doesn't appear anywhere in the issue.
