### ISSUE TITLE
describe_jobs does not include startedAt

### ISSUE THREAD

**Issue by aamster** [getmoto/moto#7366] opened 2024-02-19 21:13 UTC
```
import json

import boto3
from moto import mock_aws


@mock_aws
def test():
    batch_client = boto3.client('batch')
    ec2_client = boto3.client('ec2')

    vpc_id = ec2_client.create_vpc(CidrBlock="10.0.0.0/16")["Vpc"]["VpcId"]  # type: ignore
    subnet_ids = [
        ec2_client.create_subnet(VpcId=vpc_id, CidrBlock="10.0.0.0/20")["Subnet"]["SubnetId"]
        # type: ignore
    ]
    security_group_ids = [
        ec2_client.create_security_group(GroupName="test", Description="test", VpcId=vpc_id)[
            "GroupId"
        ]
    ]
    iam_client = boto3.client("iam")
    iam_role_arn = iam_client.create_role(
        RoleName="foo",
        AssumeRolePolicyDocument=json.dumps(
            {
                "Version": "2012-10-17",
                "Statement": [
                    {
                        "Effect": "Allow",
                        "Principal": {"Service": "batch.amazonaws.com"},
                        "Action": "sts:AssumeRole",
                    },
                    {
                        "Effect": "Allow",
                        "Principal": {"Service": "ec2.amazonaws.com"},
                        "Action": "sts:AssumeRole",
                    },
                ],
            }
        ),
    )["Role"]["Arn"]
    instance_profile_arn = iam_client.create_instance_profile(InstanceProfileName="foo")[
        "InstanceProfile"
    ]["Arn"]

    ce_arn = batch_client.create_compute_environment(
        computeEnvironmentName="test",
        type="MANAGED",
        state="ENABLED",
        computeResources={
            "type": "EC2",
            "minvCpus": 0,
            "maxvCpus": 256,
            "desiredvCpus": 0,
            "instanceTypes": ["optimal"],
            "subnets": subnet_ids,
            "securityGroupIds": security_group_ids,
            "instanceRole": instance_profile_arn,
            "tags": {"Name": "test"},
        },
        serviceRole=iam_role_arn,
    )["computeEnvironmentArn"]

    job_queue_arn = batch_client.create_job_queue(
        state="ENABLED",
        jobQueueName="test",
        priority=1,
        computeEnvironmentOrder=[
            {
                "order": 1,
                "computeEnvironment": ce_arn,
            }
        ],
    )["jobQueueArn"]

    job_definition_arn = batch_client.register_job_definition(
        jobDefinitionName="test",
        type="container",
        containerProperties={
            "resourceRequirements": [
                {"type": "MEMORY", "value": "1024"},
                {"type": "VCPU", "value": "1"},
            ],
            "image": "test",
        },
    )["jobDefinitionArn"]

    job_id = batch_client.submit_job(
        jobName="test",
        jobQueue=job_queue_arn,
        jobDefinition=job_definition_arn,
    )["jobId"]

    describe_job_response = batch_client.describe_jobs(jobs=[job_id])

    # in moto 4.2, startedAt exists
    # in moto >= 5.0, it doesn't
    print(describe_job_response["jobs"][0].get("startedAt"))

```

**Comment by bblommers** [comment] 2024-02-19 21:42
Hi @aamster! The `submit_job` starts a Docker-container behind the scenes to process the job, and the `startedAt`-attribute is only set when that Docker-job actually begins the execution.

So you may just be looking at a slight delay in when the job starts - the attribute is returned if you wait for one second for Docker to catch up:
```
    from time import sleep
    sleep(1)

    describe_job_response = batch_client.describe_jobs(jobs=[job_id])
    print(describe_job_response["jobs"][0].get("startedAt"))
```

**Comment by aamster** [comment] 2024-02-19 22:00
Hi @bblommers 

1. We never encountered this with moto 4.2, and just by switching to moto 5 we encounter this problem
2. We are actually using `@mock_aws(config={'batch': {'use_docker': False}})`. Actually I cannot reproduce if I update the example in the description to use this. But our actual code is more complicated and uses mock efs, and I still can reproduce with that.
3. Yes, if I add `time.sleep(1) then `startedAt` is populated even in the actual, more complicated code that uses efs. But this wasn't necessary in moto 4.2

**Comment by bblommers** [comment] 2024-02-19 22:52
When using `'use_docker': False` I can't reproduce it either. That does make sense, because that implementation sets the `startedAt`-attribute immediately, so there wouldn't be any delays.

Is it possible that the Batch-tests are actually executed in Docker? Or in other words: was Docker disabled for performance reasons, or because the calls would actually fail when run inside Docker?

Considering you're describing a setup with both batch and EFS tests, I assume that there are multiple `mock_aws` decorators.
If they are nested, this behaviour could be explained if only the first mock disables Docker. But if the second `mock_aws` decorator starts while the first is still active, the configuration is reset. So unless you explicitly specify `'use_docker': False` again, subsequent tests that run while the second/inner mock is active will run against Docker.

As an simplified example:
```
mock_aws_1 = mock_aws(use_docker=False)
mock_aws_1.start()

# some other tests/fixtures/whatever
# batch would be executed without docker

mock_aws_2 = mock_aws()
# second decorator starts, maybe as part of another fixture
# the configuration is reset here, so it sets use_docker=True for the duration of the inner decorator

mock_aws_2.start()
# EFS tests
# Batch tests - are now run against Docker
```

**Comment by bblommers** [comment] 2024-02-19 23:19
Happy to help @aamster! Sounds like this is resolved, so I'll close this - but feel free to reach out if you run into any other issues.

**Closed by bblommers** 2024-02-19 23:19 UTC
Labels: question
