### ISSUE TITLE
logs get_query_results

### ISSUE THREAD

**Issue by premtiwari14f** [getmoto/moto#6385] opened 2023-06-09 14:09 UTC
i am getting in get_query_results

code

import boto3
import time
from moto import mock_logs
from unittest import TestCase

@mock_logs
class TestCloudWatchLogs(TestCase):
    def setUp(self):
        # Create a CloudWatch Logs client
        self.client = boto3.client('logs', region_name="eu-west-1")

        # Create a log group and log stream
        self.log_group_name = 'your_log_group_name'
        self.log_stream_name = 'your_log_stream_name'
        self.client.create_log_group(logGroupName=self.log_group_name)
        self.client.create_log_stream(
            logGroupName=self.log_group_name,
            logStreamName=self.log_stream_name
        )

        

        # Put sample log events
        self.client.put_log_events(
            logGroupName=self.log_group_name,
            logStreamName=self.log_stream_name,
            logEvents=[
                {
                    'timestamp': int(time.time() * 1000),
                    'message': 'Log message 1'
                },
                {
                    'timestamp': int(time.time() * 1000),
                    'message': 'Log message 2'
                }
            ]
        )

        
    def test_cloudwatch_logs_query(self):
        print('done')

        # Define the query string
        query = "fields @timestamp, @message | filter @message like 'Log'"

        # Start the query
        response = self.client.start_query(
            logGroupName=self.log_group_name,
            startTime=int((time.time() - 3600) * 1000),  # Start time (e.g., 1 hour ago)
            endTime=int(time.time() * 1000),  # End time (current time)
            queryString=query
        )
        
        # Retrieve the query ID
        query_id = response['queryId']
        print('==========')
        print(response)
        
        # Wait for the query to complete
        while True:
            response = self.client.get_query_results(queryId=query_id)
            status = response['status']
            print(response)
            
            if status == 'Complete':
                break
            
            time.sleep(1)  # Wait for 1 second before checking again
        
        # Process the query results
        results = response['results']
        log_messages = [result[1]['value'] for result in results]
        
        print(log_messages)

        # Assertions
        self.assertEqual(len(log_messages), 2)
        self.assertIn('Log message 1', log_messages)
        self.assertIn('Log message 2', log_messages)

        
        
        
        ----------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\PremTiwari\AppData\Roaming\Python\Python311\site-packages\moto\core\models.py", line 124, in wrapper
    result = func(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PremTiwari\Desktop\utopus\Project\latency\fx-api-postprocessing-latency-tracker\tests\test_cw_parser.py", line 71, in test_cw_parser_run_query
    response = client.get_query_results(
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PremTiwari\AppData\Roaming\Python\Python311\site-packages\botocore\client.py", line 530, in _api_call
    return self._make_api_call(operation_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PremTiwari\AppData\Roaming\Python\Python311\site-packages\botocore\client.py", line 947, in _make_api_call
    http, parsed_response = self._make_request(
                            ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PremTiwari\AppData\Roaming\Python\Python311\site-packages\botocore\client.py", line 970, in _make_request
    return self._endpoint.make_request(operation_model, request_dict)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PremTiwari\AppData\Roaming\Python\Python311\site-packages\botocore\endpoint.py", line 119, in make_request
    return self._send_request(request_dict, operation_model)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PremTiwari\AppData\Roaming\Python\Python311\site-packages\botocore\endpoint.py", line 202, in _send_request
    while self._needs_retry(
          ^^^^^^^^^^^^^^^^^^
  File "C:\Users\PremTiwari\AppData\Roaming\Python\Python311\site-packages\botocore\endpoint.py", line 354, in _needs_retry
    responses = self._event_emitter.emit(
                ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PremTiwari\AppData\Roaming\Python\Python311\site-packages\botocore\hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PremTiwari\AppData\Roaming\Python\Python311\site-packages\botocore\hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PremTiwari\AppData\Roaming\Python\Python311\site-packages\botocore\hooks.py", line 239, in _emit
    response = handler(**kwargs)
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\PremTiwari\AppData\Roaming\Python\Python311\site-packages\botocore\retryhandler.py", line 207, in __call__
    if self._checker(**checker_kwargs):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PremTiwari\AppData\Roaming\Python\Python311\site-packages\botocore\retryhandler.py", line 284, in __call__
    should_retry = self._should_retry(
                   ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PremTiwari\AppData\Roaming\Python\Python311\site-packages\botocore\retryhandler.py", line 307, in _should_retry
    return self._checker(
           ^^^^^^^^^^^^^^
  File "C:\Users\PremTiwari\AppData\Roaming\Python\Python311\site-packages\botocore\retryhandler.py", line 363, in __call__
    checker_response = checker(
                       ^^^^^^^^
  File "C:\Users\PremTiwari\AppData\Roaming\Python\Python311\site-packages\botocore\retryhandler.py", line 247, in __call__
    return self._check_caught_exception(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PremTiwari\AppData\Roaming\Python\Python311\site-packages\botocore\retryhandler.py", line 416, in _check_caught_exception
    raise caught_exception
  File "C:\Users\PremTiwari\AppData\Roaming\Python\Python311\site-packages\botocore\endpoint.py", line 278, in _do_get_response
    responses = self._event_emitter.emit(event_name, request=request)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PremTiwari\AppData\Roaming\Python\Python311\site-packages\botocore\hooks.py", line 412, in emit
    return self._emitter.emit(aliased_event_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PremTiwari\AppData\Roaming\Python\Python311\site-packages\botocore\hooks.py", line 256, in emit
    return self._emit(event_name, kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PremTiwari\AppData\Roaming\Python\Python311\site-packages\botocore\hooks.py", line 239, in _emit
    response = handler(**kwargs)
               ^^^^^^^^^^^^^^^^^
  File "C:\Users\PremTiwari\AppData\Roaming\Python\Python311\site-packages\moto\core\botocore_stubber.py", line 61, in __call__
    status, headers, body = response_callback(
                            ^^^^^^^^^^^^^^^^^^
  File "C:\Users\PremTiwari\AppData\Roaming\Python\Python311\site-packages\moto\core\responses.py", line 231, in dispatch
    return cls()._dispatch(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\PremTiwari\AppData\Roaming\Python\Python311\site-packages\moto\core\responses.py", line 375, in _dispatch
    return self.call_action()
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\PremTiwari\AppData\Roaming\Python\Python311\site-packages\moto\core\responses.py", line 480, in call_action
    raise NotImplementedError(f"The {action} action has not been implemented")
NotImplementedError: The get_query_results action has not been implemented

**Comment by bblommers** [comment] 2023-06-10 10:36
Hi @premtiwari14f, thanks for raising this! Looks like this is a duplicate of https://github.com/getmoto/moto/issues/5015, so I'm going to close this one. Feel free to subscribe to the existing issue, so you can receive updates when there is any progress.

**Closed by bblommers** 2023-06-10 10:36 UTC
