### ISSUE TITLE
Responses have invalid date header if locale is non-english

### ISSUE THREAD

**Issue by ferdynator** [getmoto/moto#2438] opened 2019-10-01 18:01 UTC
Responses using [this method for a timestamp](https://github.com/spulec/moto/blob/4497f18c1a32653db601a6da0e0a9cc036383605/moto/core/utils.py#L186) will contain a localized datestring that botocore cannot process because it uses the, locale unaware, [`dateutil.parser.parse` method](https://github.com/boto/botocore/blob/develop/botocore/utils.py#L568).

    > import locale
    > locale.setlocale(locale.LC_ALL, '')
    'LC_CTYPE=en_US.UTF-8;LC_NUMERIC=de_DE.UTF-8;LC_TIME=de_DE.UTF-8;LC_COLLATE=en_US.UTF-8;LC_MONETARY=de_DE.UTF-8;LC_MESSAGES=en_US.UTF-8;LC_PAPER=de_DE.UTF-8;LC_NAME=de_DE.UTF-8;LC_ADDRESS=de_DE.UTF-8;LC_TELEPHONE=de_DE.UTF-8;LC_MEASUREMENT=de_DE.UTF-8;LC_IDENTIFICATION=de_DE.UTF-8'
    > datetime.datetime.now().strftime('%a, %d %b %Y %H:%M:%S GMT')
    'Di, 01 Okt 2019 19:21:57 GMT'
    > from dateutil import parser
    > parser.parse('Di, 01 Okt 2019 19:21:57 GMT')
    Traceback (most recent call last):
        raise ValueError("Unknown string format:", timestr)
    ValueError: ('Unknown string format:', 'Di, 01 Okt 2019 19:21:57 GMT')

Setting the locale to English before running any test with moto fixes the issue:

    import locale
    locale.setlocale(locale.LC_ALL, 'en_US.utf8')

IMHO this should at least be documented, maybe we can even fix it?

**Comment by spulec** [comment] 2019-10-08 01:49
Hmmm, that is annoying. Thanks for opening.

Any thoughts on what a fix would be? I'm a bit nervous about globally changing the locale.

**Comment by ferdynator** [comment] 2019-10-08 07:24
Good question. I agree, globally changing should be the last option. From the python docs:

> If, when coding a module for general use, you need a locale independent version of an operation that is affected by the locale (such as certain formats used with time.strftime()), you will have to find a way to do it without using the standard library routine. Even better is convincing yourself that using locale settings is okay. Only as a last resort should you document that your module is not compatible with non-C locale settings. - [locale](https://docs.python.org/3.7/library/locale.html#background-details-hints-tips-and-caveats)

So I guess using the `datetime` package is not an option then. 

It looks like the `time` package can be used to get an English date-string but it has a different format. The result of `time.asctime()` can be parsed by the `datetime.parser` though:

    >>> import time, locale
    >>> from dateutil import parser
    >>> locale.setlocale(locale.LC_ALL, '')
    'LC_CTYPE=en_US.UTF-8;LC_NUMERIC=de_DE.UTF-8;...'
    >>> time.asctime(time.gmtime())
    'Tue Oct  8 07:19:52 2019'
    >>> parser.parse('Tue Oct  8 07:19:52 2019')
    datetime.datetime(2019, 10, 8, 7, 19, 52)

So maybe that is a way to go here...

**Comment by spulec** [comment] 2020-02-23 04:07
I suppose we could store the current locale, change it to `en_US.utf8`, and then set it back as part of this method. This doesn't seem too horrible. It would be ideal if there was some way to pass a locale to `strftime`, but that doesn't seem possible.

**Comment by bblommers** [comment] 2023-01-17 13:46
Hi @ferdynator, is this still an issue? I cannot reproduce this anymore by setting `locale.setlocale(locale.LC_ALL, '')` locally, and it looks like botocore do now pass a timezone when parsing; https://github.com/boto/botocore/commit/ed7cf156855f4468b0e86e724cb97186fcbd3516

**Comment by bblommers** [comment] 2023-02-18 00:04
Going to assume it is indeed fixed, so I'll close this. Let me know if this is still an issue though.

**Closed by bblommers** 2023-02-18 00:04 UTC
Labels: question

**Comment by bblommers** [comment] 2024-01-26 22:50
Hi @rank-p, thanks for the repro-case. This should be fixed in #7254, and part of moto >= 4.2.14.dev29.

Let us know if you run into any (other) issues!
