### ISSUE TITLE
mock_aws() with scope='function' is not working along with @pytest.mark.parametrize

### ISSUE THREAD

**Issue by Manisha28696** [getmoto/moto#7309] opened 2024-02-05 12:16 UTC
I'm using the latest version of Moto 5.0.1v and Python version 3.9.2v

My case:
1. In one of my unit tests, I'm using mock_aws() as a fixture with scope='function'  which creates dynamodb table and inserts a few items in it.
2. And the unit test has @pytest.mark.parametrize with few inputs.

With the above 2 functionalities, my unit test is failing from 2nd i/p(1st i/p has passed) with ResourceIsInUse Exception which was not in the case of moto versions <5.0

My understanding is that the mocked dynamodb is not being cleared/deleted after each i/p run which was happening in previous versions of Moto.

Can someone help me out with this?

**Comment by bblommers** [comment] 2024-02-05 13:14
Hi @Manisha28696, can you post a reproducible test case?

I've just tried it with a simple fixture that only creates an S3 bucket, and that seems to work as expected. The test is invoked twice, but there is always only one S3 bucket (the one created in the fixture).
```
import boto3
import pytest
from moto import mock_aws
from uuid import uuid4


@pytest.fixture(scope="function")
def mockaws():
    with mock_aws():
        s3 = boto3.client("s3", "us-east-1")
        s3.create_bucket(Bucket=str(uuid4())[0:6])
        yield


@pytest.mark.parametrize("nr", ["1", "2"])
def test_parametrized(nr, mockaws):
    s3 = boto3.client("s3", "us-east-1")
    assert len(s3.list_buckets()["Buckets"]) == 1
```

**Comment by Manisha28696** [comment] 2024-02-06 05:51
Hi @bblommers, I think I misunderstood the issue. The issue seems to be mock_aws() being used in different scopes at the same time. This gives ResourceInUseException with the latest version of the moto, earlier with <5.0v it was working fine

For example, I have a use case like below:

**conftest.py**


```
@pytest.fixture(scope='module')
def mockiam(): # Here this mockiam will be used in different test files as well, so I have declared it as a different fixture
    with mock_aws():
        iam = boto3.client('iam')
        # Create iam role required
        iams = iam.create_role(RoleName='test_iam', AssumeRolePolicyDocument='string')
        yield

@pytest.fixture(scope="function")
def mockaws(request, mockiam):
    with mock_aws():
        dynamodb = boto3.resource('dynamodb')
        billing_mode = 'PAY_PER_REQUEST'

        # Creating attic schema catalog table
        key_schema = [{'AttributeName': 'name', 'KeyType': 'HASH'}]
        attr_definition = [{'AttributeName': 'name', 'AttributeType': 'S'}]
        dynamodb.create_table(TableName='test_table', KeySchema=key_schema,
                                AttributeDefinitions=attr_definition, BillingMode=billing_mode)

        table = dynamodb.Table('test_table')

        for item in request.param:
            table.put_item(Item=item)
        yield
```

**test_sample.py**

```
import pytest
import boto3

TABLE_ITEMS = [
    {
        'name': 'name1',
        'col': 'col1',
    },
    {
        'name': 'name2',
        'col': 'col2',
    }
]

@pytest.mark.parametrize('mockaws', [TABLE_ITEMS], indirect=True)
@pytest.mark.parametrize("nr", ["1", "2"])
def test_parametrized(nr, mockaws):
    # client.cache_clear()
    # make the connection to dynamodb
    dynamodb = boto3.resource('dynamodb')

    # select the table
    table = dynamodb.Table("test_table")

    # get item from database
    item = table.get_item(Key={"name": 'name1'})
    assert item['Item'] == {'name': 'name1', 'col': 'col1'}
```

**Comment by Manisha28696** [comment] 2024-02-06 06:13
When I change the scope of mockiam to function it is working. But I want it to be of module scope as I'm using it in other test files

**Comment by bblommers** [comment] 2024-02-07 18:56
@Manisha28696 That behaviour is by design, I'm afraid. With the new `mock_aws`-decorator, the underlying data (such as DynamoDB tables) is only deleted when the outer decorator finishes.

It isn't very pretty, but you could always manually delete the table? That would prevent you from having to re-work your fixtures.
```
@pytest.fixture(scope="function")
def mockaws(request, mockiam):
    with mock_aws():
        dynamodb = boto3.resource('dynamodb')
        billing_mode = 'PAY_PER_REQUEST'

        # Creating attic schema catalog table
        .. as before ..
        yield

        # Delete the table at the end of the fixture/test
        dynamodb.delete_table(TableName="test_table")
```

**Comment by Manisha28696** [comment] 2024-02-08 05:45
@bblommers In the given example, it was only dynamodb table but in the original use case I have multiple services defined in mockaws fixture and SSM parameter, IAM as separate fixtures.

With your suggested way I have to delete lot things, for now I went with an approach of making all fixtures scope as function and it is working as required.

Isn't there a way to have a feature which resets services used inside a particular fixture after it's scope?

**Comment by bblommers** [comment] 2024-02-08 21:41
@Manisha28696 There is no easy way for us to track which services are used, no. That is made even more difficult for features that create resources in other services (for example AWSLambda creating CloudWatch Logs).

The easiest way to make this work (if I understand your use-case correctly) may be to use the internal API's, and directly reset the backends:
```
from moto.core import DEFAULT_ACCOUNT_ID
from moto.iot import iot_backends

iot_backends[DEFAULT_ACCOUNT_ID].reset()
```

Every service exposes it's backend in the same way, if you want to do this for other services as well.

**Comment by bblommers** [comment] 2024-02-18 15:59
I'm going to assume that this has been resolved, so I'll close this. Do let us know if you run into any other issues.

**Closed by bblommers** 2024-02-18 15:59 UTC
Labels: debugging
