### ISSUE TITLE
Moto (DynamoDB) doesn't match that of AWS 

### ISSUE THREAD

**Issue by chadmiracle** [getmoto/moto#7345] opened 2024-02-15 19:50 UTC
Moto 5.0.1
boto3 1.34.37

Reproduce: 

Basic Usage, Dynamo Create table

```
   @mock_aws
    def test_dynamo(self):
        """Must satisfy all of the required fields
                TableName,AttributeDefinitions,KeySchema,ProvisionedThroughput,Tags,StreamSpecification,BillingMode,GlobalSecondaryIndexes,LocalSecondaryIndexes
        """
        timestamp = dt.now()
        epoch = int(time.time())
        TableName = "my_test_" + str(epoch)

        LocalSecondaryIndexes = [
            {
            "IndexName" : "local_index"
            },
            {
            "KeySchema": [ {
            "AttributeName": "Creator",
            "KeyType": "RANGE"
                    }
                ]
            },
            {
                "Projection":"ALL"
            },
            {
                "ProvisionedThroughput" : {
                    'ReadCapacityUnits': 5,
                    'WriteCapacityUnits': 5,
                }
            }
        ]

        GlobalSecondaryIndexes = [
            {
            "IndexName" : "global_index"
            },
            {
            "KeySchema": [ {
            "AttributeName": "ComicBook",
            "KeyType": "RANGE"
                    }
                ]
            },
            {
                "Projection":"ALL"
            },
            {
                "ProvisionedThroughput" : {
                    'ReadCapacityUnits': 5,
                    'WriteCapacityUnits': 5,
                }
            }
        ]

        BillingMode = "PAY_PER_REQUEST"

        StreamSpecification = {"StreamEnabled": False}

        Tags = [
            {"Creator": "cmiracle"},
            {"Created_Epoch": timestamp},
            {"Environment": "Development"}
        ]
        AttributeDefinitions=[
        {
            'AttributeName': 'UUID',
            'AttributeType': 'S',
        },
        {
            'AttributeName': 'ComicBook',
            'AttributeType': 'S',
        },
        # {
        #     'AttributeName': 'Creator',
        #     'AttributeType': 'S',
        # },
        # {
        #     'AttributeName': 'Year',
        #     'AttributeType': 'N',
        # }
        ]

        KeySchema = [
            {
                'AttributeName': 'UUID',
                'KeyType': 'HASH'
            },
            {
                'AttributeName': 'ComicBook',
                'KeyType': 'RANGE'
            }
            # },
            # {
            #     'AttributeName': 'Creator',
            #     'KeyType': 'RANGE'
            # },
            # {
            #     'AttributeName': 'Year',
            #     'KeyType': 'RANGE'
            # }
        ]

        ProvisionedThroughput={
            'ReadCapacityUnits': 5,
            'WriteCapacityUnits': 5,
        }

        try:
            # We're passing back the result of the actual table Creation function which contains the AWS return values
            # From here, we can parse the return to make sure expected values are as such
            test_result = ds.dynamo_createtable(TableName,AttributeDefinitions,KeySchema,ProvisionedThroughput,Tags,StreamSpecification,BillingMode,GlobalSecondaryIndexes,LocalSecondaryIndexes)
            # print(test_result['TableDescription'])
        except Exception as e:
            raise(f"An error executing Create Table: {e}")
```

With this, it runs, and returns a Response.  But the Local and Global Secondary Indexes are empty.  BillingMode is wrong.

If you uncomment out the Attribute Names in Key Schema and run it again, Moto doesn't throw an error.  If you run this without @mock_aws, AWS will throw an error because you can't have more Attributes than keys.

Should I downgrade Boto or Moto?  We're looking to use Moto to fully test our AWS code before running them in AWS itself.

**Comment by bblommers** [comment] 2024-02-15 20:21
Hi @chadmiracle, are you able to create a stand-alone reproducible testcase? The `ds.dynamo_createtable` presumably does some parsing/mangling of the arguments, because passing them to boto3 directly results in a whole lot of validation errors.

**Comment by chadmiracle** [comment] 2024-02-15 20:37
I run exactly what I posted directly against AWS using Boto3; there are no validation errors.

**Comment by bblommers** [comment] 2024-02-15 21:01
What does the `dynamo_createtable`-method do, that you're using in your example? As that is not a boto3-method as far as I know.

**Comment by chadmiracle** [comment] 2024-02-15 21:03
It's in different libraries, so that ends up calling

`
    def dynamo_createtable(self,TableName,AttributeDefinitions,KeySchema,ProvisionedThroughput,Tags,StreamSpecification,BillingMode,GlobalSecondaryIndexes,LocalSecondaryIndexes   ):
        print("Initiating Creation of Dynamo Table")
        dclient = self.session.client('dynamodb')

        response = dclient.create_table(TableName=TableName,AttributeDefinitions=AttributeDefinitions,KeySchema=KeySchema,ProvisionedThroughput=ProvisionedThroughput)
`

**Comment by bblommers** [comment] 2024-02-15 21:17
The `dynamo_createtable` never uses the the Indexes or BillingMode:
```
response = dclient.create_table(
    TableName=TableName,
    AttributeDefinitions=AttributeDefinitions,
    KeySchema=KeySchema,
    ProvisionedThroughput=ProvisionedThroughput
)
```
So I'm not surprised that these attributes are also missing from the response.

**Comment by chadmiracle** [comment] 2024-02-16 13:28
Fair enough but Moto still fails to validate the AttributeDefinitions and KeySchema.  If I uncomment out those items in the KeySchema, I should get an error from Moto and I do not.

**Comment by bblommers** [comment] 2024-02-16 19:25
There are at least four scenarios here, as far as I can see:
 - An attribute is defined by KeySchema, but not in AttributeDefinitions --> coveredy by Moto
 - An attribute is defined in AttributeDefinitions, but not in KeySchema -->  covered by Moto
 - An attribute is present in both, but mistyped --> covered by Moto

The test case above is a fourth scenario:
 - There are too many elements in the KeySchema. Whether or not the additional element is covered by AttributeDefinitions is irrelevant, as AWS will always complain about the KeySchema-length first.

I've raised a PR to cover this error case, so Moto will throw the correct exception after that's merged.

**Closed** 2024-02-16 20:35 UTC
Labels: debugging
