### ISSUE TITLE
Add lakeformation support

### ISSUE THREAD

**Issue by henriblancke** [getmoto/moto#5979] opened 2023-02-24 19:09 UTC
Add support for mocking the [lakeformation](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/lakeformation.html) client

**Comment by bblommers** [comment] 2023-02-24 22:08
Is this a question? A command? Are you stating your intent?

Regardless, it's a duplicate of #5960 . If you want to see support for features not yet listed, please add them there.

**Closed by bblommers** 2023-02-24 22:08 UTC
Labels: enhancement
